color: null
fieldLayouts:
  0a7b95b1-ab07-4724-a822-cbf5b96faf96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98a5c5c3-c246-4d3b-ad90-14fcc1380ece
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d355d5b-6b71-46c6-a406-c9799ed6941d # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9041742d-2623-4399-ae8d-1043a52d2e70
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3800b6e0-2f15-441d-beee-1fa3475d3169
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
