color: null
fieldLayouts:
  f44086de-0b85-48de-af22-e8b0358d8f81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: efafb9c5-4456-48d8-b97b-8a5213005311
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7cca4df9-5efb-4d22-9e7c-ee92941e8d32
        userCondition: null
handle: kleuren
hasTitleField: true
icon: ''
name: Kleuren
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
