color: null
fieldLayouts:
  d2d37d79-0a39-4271-9bc5-23bfc2856397:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9035ac5c-3e44-49c0-95ed-fd994d9944de
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6cd3c6c6-8cd0-44a7-8dd3-09632aa47b02 # Blockbuilder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19cbc308-6edd-4c06-a302-4bcb984a04f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 236de5ae-4d8e-40c8-845e-a9385bb46773
        userCondition: null
handle: nieuwePagina
hasTitleField: false
icon: ''
name: 'Nieuwe pagina'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
