color: null
fieldLayouts:
  dcaa50d3-0b02-4271-9f32-a1b0054090eb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 933a7baf-842c-451c-bf68-6b63e1738fa3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d355d5b-6b71-46c6-a406-c9799ed6941d # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db17c72e-984e-40ea-ab9e-87675ca4fed9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7784c795-aace-43ac-bc9e-71f273cc6dee # Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c5ea15a-5297-48a4-baf5-2963bcf84b8a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 42de7d67-ef38-47a5-bb2b-a5d67a199c18
        userCondition: null
handle: tekstAfbl
hasTitleField: true
icon: ''
name: 'Tekst + afbl'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
