fieldLayouts:
  aa26cd34-73d0-4261-a17e-e88ffbcd1aa7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d9d9d03e-ec07-40f8-8f51-fbe7f8298bf3 # Titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea9890c4-d2c5-4fd1-9a6f-c86d785f9fb0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d355d5b-6b71-46c6-a406-c9799ed6941d # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d14acf8e-1b8c-4b5b-8078-a51befb21b1a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5c8bf00-e14e-42d6-9122-62c5d0ae3c1e # Icoon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cecddae0-dc9b-4626-a286-9b7e502dc5ee
            userCondition: null
            warning: null
            width: 100
        name: footer
        uid: dc38917e-ebbd-4ed9-8b09-487b53eb1784
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
