defaultPlacement: end
enableVersioning: true
entryTypes:
  - f9c5dc8a-0d91-42d1-a942-b9c29171710d # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a991982-8b5b-44cc-bf3a-4c08ded12bd5: # ShneakyShop
    enabledByDefault: true
    hasUrls: true
    template: _snippits\_contact.twig
    uriFormat: contact
type: single
