defaultPlacement: end
enableVersioning: true
entryTypes:
  - 940896b3-8910-4e32-8e3a-4978629f090b # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a991982-8b5b-44cc-bf3a-4c08ded12bd5: # ShneakyShop
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
