defaultPlacement: end
enableVersioning: true
entryTypes:
  - f27548b2-728f-420d-a867-bb344879dfe3 # Kleuren
handle: kleuren
maxAuthors: 1
name: Kleuren
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a991982-8b5b-44cc-bf3a-4c08ded12bd5: # ShneakyShop
    enabledByDefault: true
    hasUrls: true
    template: kleuren/_entry
    uriFormat: 'kleuren/{slug}'
structure:
  maxLevels: null
  uid: 965f490d-073f-4877-a219-f83c481c1cb7
type: structure
