defaultPlacement: end
enableVersioning: true
entryTypes:
  - cf95cbf0-bf08-46fc-8193-5343b4f6c1ba # Nieuwe pagina
handle: nieuwePagina
maxAuthors: 1
name: 'Nieuwe pagina'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a991982-8b5b-44cc-bf3a-4c08ded12bd5: # ShneakyShop
    enabledByDefault: true
    hasUrls: true
    template: _snippits/_nieuwePag.twig
    uriFormat: 'nieuwe-pagina/{slug}'
structure:
  maxLevels: null
  uid: 45e0b092-50e1-487e-a6db-6da365fc6241
type: structure
