defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1d3196e2-8fbe-4b0d-a22f-41284b7a7633 # TypeArt
handle: typeart
maxAuthors: 1
name: TypeArt
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a991982-8b5b-44cc-bf3a-4c08ded12bd5: # ShneakyShop
    enabledByDefault: true
    hasUrls: true
    template: typeart/_entry
    uriFormat: 'typeart/{slug}'
structure:
  maxLevels: null
  uid: 4fb87c29-bdc2-47bf-b185-c93f20ea4a10
type: structure
